//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModularBOT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModularBOT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;StatusOverview&quot;&gt;
        ///    &lt;h1&gt;STATUS: &lt;span id=&quot;status&quot; class=&quot;&quot;&gt;--&lt;/span&gt;&lt;/h1&gt;
        ///    &lt;p class=&quot;runtime_details&quot;&gt;&lt;b&gt;DURATION:&lt;/b&gt; &lt;span class=&quot;runtime&quot;&gt;-- Days -- Hours -- Minutes&lt;/span&gt; | &lt;b&gt;Guilds:&lt;/b&gt; &lt;span class=&quot;g_avail&quot;&gt;----&lt;/span&gt;/&lt;span class=&quot;g_total&quot;&gt;----&lt;/span&gt;&lt;/p&gt;
        ///&lt;/div&gt;
        ///&lt;div class=&quot;ticketgrid&quot;&gt;
        ///    &lt;div class=&quot;bn_conf&quot;&gt;&lt;h2&gt;Configuration&lt;/h2&gt;&lt;/div&gt;
        ///    &lt;div class=&quot;bn_management&quot;&gt;&lt;h2&gt;Instance Settings&lt;/h2&gt;&lt;/div&gt;
        ///    &lt;div class=&quot;bn_commands&quot;&gt;&lt;h2&gt;Commands&lt;/h2&gt;&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0&quot;&gt;
        ///
        ///	&lt;link rel=&quot;preload&quot; href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;display=swap&quot; as=&quot;style&quot;&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;display=swap&quot; media=&quot;print&quot; onload=&quot;this.media=&apos;all&apos;&quot;&gt;
        ///	&lt;noscript&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; href=&quot;https://fonts.googleapis.com/css2?family=Roboto:wght@300;400; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PageTemplate {
            get {
                return ResourceManager.GetString("PageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RMSoftwareICO {
            get {
                object obj = ResourceManager.GetObject("RMSoftwareICO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
